# -*- coding: utf-8 -*-
from django.utils.translation import ugettext_lazy as _

td = (
  _("Advanced")
, _("name")
, _("map")
, _("maps")
, _("Area number")
, _("url")
, _("Area path")
, _("description")
, _("map area")
, _("map areas")
, _("SEO settings")
, _("This identifier is already used by an other page.")
, _("This URL is already taken by an other page.")
, _("This slug is already used by an other page at the same level.")
, _("Menu structure")
, _("Page type")
, _("page type")
, _("Status")
, _("Mark selected objects as published")
, _("Page")
, _("Pages")
, _("Published")
, _("Draft")
, _("parent")
, _("You can also change the parent by dragging the page in the list.")
, _("status")
, _("publication date")
, _("When the page should go live, status must be \"Published\".")
, _("publication end date")
, _("show in navigation")
, _("include in search engine sitemaps")
, _("page identifier")
, _("A unique identifier that is used for linking to this page.")
, _("creation date")
, _("last modification")
, _("URL Node")
, _("URL Nodes")
, _("title")
, _("slug")
, _("The slug is used in the URL of the page")
, _("Override URL")
, _("Override the target URL. Be sure to include slashes at the beginning and at the end if it is a local URL. This affects both the navigation and subpages' URLs.")
, _("keywords")
, _("page title")
, _("key")
, _("A short name to identify the layout programmatically")
, _("Layout")
, _("Layouts")
, _("The selected page cannot have sub pages.")
, _("Content")
, _("Flat Page")
, _("Flat Pages")
, _("Redirect settings")
, _("Normal redirect")
, _("Permanent redirect (for SEO ranking)")
, _("New URL")
, _("Redirect type")
, _("Use 'normal redirect' unless you want to transfer SEO ranking to the new page.")
, _("Redirect")
, _("Redirects")
, _("Plain text")
, _("XML")
, _("HTML")
, _("File type")
, _("File contents")
, _("Plain text file")
, _("Plain text files")
, _("History")
, _("View on site")
, _("Please correct the error below.")
, _("Please correct the errors below.")
, _("{No rendering defined for class '%s'}")
, _("Error:")
, _("Main content")
, _("Sidebar content")
, _("Related content")
, _("Slot")
, _("A short name to identify the placeholder in the template code.")
, _("Role")
, _("Admin title")
, _("Placeholder")
, _("Placeholders")
, _("Contentitem link")
, _("Contentitem links")
, _("Language")
, _("Code")
, _("Code snippet")
, _("Code snippets")
, _("Allow posting new comments")
, _("Comments area")
, _("Disqus comments area")
, _("Disqus comments areas")
, _("Form")
, _("Form link")
, _("Form links")
, _("Media")
, _("File URL")
, _("Specify the URL of an online document, for example a PDF or DOCX file.")
, _("Width")
, _("Specify the size in pixels, or a percentage of the container area size.")
, _("Height")
, _("Specify the size in pixels.")
, _("Embedded document")
, _("Page URL")
, _("Markup")
, _("markup")
, _("Markup code")
, _("%s items")
, _("Enter the URL of the online content to embed (e.g. a YouTube or Vimeo video, SlideShare presentation, etc..)")
, _("The URL is not valid for embedding content")
, _("URL to embed")
, _("Max width")
, _("Max height")
, _("Online media")
, _("Max size")
, _("pixels")
, _("Left")
, _("Center")
, _("Right")
, _("Image")
, _("Caption")
, _("Align")
, _("URL")
, _("Open in a new window")
, _("Picture")
, _("Pictures")
, _("HTML code")
, _("Enter the HTML code to display, like the embed code of an online widget.")
, _("Publication settings")
, _("Title")
, _("Contents")
, _("Shared content")
, _("text")
, _("Text")
, _("You may use Twitter markup here, such as a #hashtag or @username.")
, _("Twitter user")
, _("Number of results")
, _("Footer text")
, _("Include retweets")
, _("Include replies")
, _("Recent twitter entries")
, _("Search for")
, _("Twitter search feed")
, _("loading tweets...")
, _("There are no options to configure for this element.")
, _("Loading layout data...")
, _("Orphaned content")
, _("There are no placeholders in this template.")
, _("Add")
, _("Copy language")
, _("Placeholder empty")
, _("This placeholder is empty")
, _("No items added to this field yet.")
, _("Value should be a number or percentage.")
, _("fluent_pages")
, _("Fluent_pages")
, _("edit")
, _("move failed")
, _("Error while loading the data from the server")
, _("Grid view")
, _("Tree view")
, _("future")
, _("now")
, _("month")
, _("year")
, _("all")
, _("past")
, _("map_plugin")
, _("Form designer")
, _("Addition settings")
, _("template file")
) 